In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('input/train.csv')
test = pd.read_csv('input/test.csv')

In [3]:
print(train.shape)
train.head()

(33126, 11)

,image_name,patient_id,sex,age_approx,anatom_site_general_challenge,diagnosis,benign_malignant,target,tfrecord,width,height
0,ISIC_2637011,IP_7279968,male,45.0,head/neck,unknown,benign,0,0,6000,4000
1,ISIC_0015719,IP_3075186,female,45.0,upper extremity,unknown,benign,0,0,6000,4000
2,ISIC_0052212,IP_2842074,female,50.0,lower extremity,nevus,benign,0,6,1872,1053
3,ISIC_0068279,IP_6890425,female,45.0,head/neck,unknown,benign,0,0,1872,1053
4,ISIC_0074268,IP_8723313,female,55.0,upper extremity,unknown,benign,0,11,6000,4000

In [4]:
print(test.shape)
test.head()

(10982, 7)

,image_name,patient_id,sex,age_approx,anatom_site_general_challenge,width,height
0,ISIC_0052060,IP_3579794,male,70.0,NaN,6000,4000
1,ISIC_0052349,IP_7782715,male,40.0,lower extremity,6000,4000
2,ISIC_0058510,IP_7960270,female,55.0,torso,6000,4000
3,ISIC_0073313,IP_6375035,female,50.0,torso,6000,4000
4,ISIC_0073502,IP_0589375,female,45.0,lower extremity,1920,1080

# Data Exploration

In [9]:
print(train.info)

<bound method DataFrame.info of          image_name  patient_id     sex  age_approx  \
0      ISIC_2637011  IP_7279968    male        45.0
1      ISIC_0015719  IP_3075186  female        45.0
2      ISIC_0052212  IP_2842074  female        50.0
3      ISIC_0068279  IP_6890425  female        45.0
4      ISIC_0074268  IP_8723313  female        55.0
...             ...         ...     ...         ...
33121  ISIC_9999134  IP_6526534    male        50.0
33122  ISIC_9999320  IP_3650745    male        65.0
33123  ISIC_9999515  IP_2026598    male        20.0
33124  ISIC_9999666  IP_7702038    male        50.0
33125  ISIC_9999806  IP_0046310    male        45.0

      anatom_site_general_challenge diagnosis benign_malignant  target  \
0                         head/neck   unknown           benign       0
1                   upper extremity   unknown           benign       0
2                   lower extremity     nevus           benign       0
3                         head/neck   unknown           benign       0
4                   upper extremity   unknown           benign       0
...                             ...       ...              ...     ...
33121                         torso   unknown           benign       0
33122                         torso   unknown           benign       0
33123               lower extremity   unknown           benign       0
33124               lower extremity   unknown           benign       0
33125                         torso     nevus           benign       0

       tfrecord  width  height
0             0   6000    4000
1             0   6000    4000
2             6   1872    1053
3             0   1872    1053
4            11   6000    4000
...         ...    ...     ...
33121         2   2592    1936
33122        11   6000    4000
33123         3   1872    1053
33124        11   1872    1053
33125         4   1872    1053

[33126 rows x 11 columns]>

In [10]:
print(test.info)

<bound method DataFrame.info of          image_name  patient_id     sex  age_approx  \
0      ISIC_0052060  IP_3579794    male        70.0
1      ISIC_0052349  IP_7782715    male        40.0
2      ISIC_0058510  IP_7960270  female        55.0
3      ISIC_0073313  IP_6375035  female        50.0
4      ISIC_0073502  IP_0589375  female        45.0
...             ...         ...     ...         ...
10977  ISIC_9992485  IP_4152479    male        40.0
10978  ISIC_9996992  IP_4890115    male        35.0
10979  ISIC_9997917  IP_2852390    male        25.0
10980  ISIC_9998234  IP_8861963    male        65.0
10981  ISIC_9999302  IP_6214039    male        30.0

      anatom_site_general_challenge  width  height
0                               NaN   6000    4000
1                   lower extremity   6000    4000
2                             torso   6000    4000
3                             torso   6000    4000
4                   lower extremity   1920    1080
...                             ...    ...     ...
10977                         torso    640     480
10978                         torso   2592    1936
10979               upper extremity    640     480
10980               lower extremity   6000    4000
10981               upper extremity   1920    1080

[10982 rows x 7 columns]>

In [5]:
trainf = pd.read_csv('input/train_folds.csv')

In [6]:
trainf.head()

,image_name,patient_id,sex,age_approx,anatom_site_general_challenge,diagnosis,benign_malignant,target,tfrecord,width,height,kfold
0,ISIC_8791163,IP_3707904,male,80.0,torso,unknown,benign,0,13,1872,1053,0
1,ISIC_6432672,IP_1153670,male,45.0,head/neck,unknown,benign,0,8,6000,4000,0
2,ISIC_4032630,IP_6341009,female,45.0,lower extremity,nevus,benign,0,4,1872,1053,0
3,ISIC_5267251,IP_3423256,female,60.0,torso,unknown,benign,0,7,5184,3456,0
4,ISIC_6251647,IP_8267064,female,30.0,torso,unknown,benign,0,12,5184,3456,0